Update steps

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -1,6 +1,29 @@
 #!/bin/bash
 set -euo pipefail
 
+# retry <number-of-retries> <command>
+function retry {
+	local retries=$1
+	shift
+	local attempts=1
+	local status=0
+
+	until "$@"; do
+		status=$?
+		echo "Exited with $status"
+		if ((retries == "0")); then
+			return $status
+		elif ((attempts == retries)); then
+			echo "Failed $attempts retries"
+			return $status
+		else
+			echo "Retrying $((retries - attempts)) more times..."
+			attempts=$((attempts + 1))
+			sleep $(((attempts - 2) * 2))
+		fi
+	done
+}
+
 PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
 
 rm -rf /tmp/service_account.json
@@ -97,6 +120,14 @@ command_string="$(
 
 args+=("${command_string}")
 display_command+=("'${command_string}'")
+
+echo "--- :docker: Pulling ${image}"
+if ! retry "${BUILDKITE_PLUGIN_CLOUD_FUNCTIONS_DOCKER_PULL_RETRIES:-3}" \
+	docker pull "${image}"; then
+	rv=$?
+	echo "--- :docker: Pull failed."
+	exit $rv
+fi
 
 echo '--- :docker: Logging "docker create" command'
 echo "$ docker create" >&2
