Update command

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -27,15 +27,15 @@ fi
 echo "${BUILDKITE_PLUGIN_BIGQUERY_GCP_PROJECT}"
 echo "${BUILDKITE_PLUGIN_BIGQUERY_DATASET_SCHEMA_DIRECTORY}"
 
-if [ -z "$BUILDKITE_PLUGIN_BIGQUERY_GCP_PROJECT" ]; then
-	echo "ERROR: bigquery project key not set"
-	exit 1
-fi
+# if [ -z "$BUILDKITE_PLUGIN_BIGQUERY_GCP_PROJECT" ]; then
+# 	echo "ERROR: bigquery project key not set"
+# 	exit 1
+# fi
 
-if [ -z "${BUILDKITE_PLUGIN_BIGQUERY_DATASET_SCHEMA_DIRECTORY}" ]; then
-	echo "ERROR: dataset schema not set"
-	exit 1
-fi
+# if [ -z "${BUILDKITE_PLUGIN_BIGQUERY_DATASET_SCHEMA_DIRECTORY}" ]; then
+# 	echo "ERROR: dataset schema not set"
+# 	exit 1
+# fi
 
 echo "--- :docker: Starting execution of docker image"
 
@@ -43,5 +43,5 @@ docker run -t --rm \
 	-v /usr/bin/buildkite-agent:/usr/bin/buildkite-agent \
 	-e dataset_schema_directory="${BUILDKITE_PLUGIN_BIGQUERY_DATASET_SCHEMA_DIRECTORY}" \
 	-e gcp_project="${BUILDKITE_PLUGIN_BIGQUERY_GCP_PROJECT}" \
-	-e credentials="${BUILDKITE_PLUGIN_BIGQUERY_GCP_SERVICE_ACCOUNT}" \
+# 	-e credentials="${BUILDKITE_PLUGIN_BIGQUERY_GCP_SERVICE_ACCOUNT}" \
 	"${image_with_tag}"
